# frozen_string_literal: true

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.

require 'simplecov'

SimpleCov.start do
  skip '/spec/'
end

require 'sepa_rator'

# Via their entry files, so the real schema-root registration path is tested.
require_relative '../sepa_rator-at/lib/sepa_rator/at'
require_relative '../sepa_rator-dk/lib/sepa_rator/dk'
require_relative '../sepa_rator-sps/lib/sepa_rator/sps'

require 'active_support/testing/time_helpers'

# Requires supporting ruby files with custom matchers and macros, etc,
# in spec/support/ and its subdirectories.
Dir[File.expand_path(File.join(__dir__, 'support', '**', '*.rb'))].each { |f| require f }

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.include ActiveSupport::Testing::TimeHelpers
  config.filter_run_when_matching :focus

  config.before(:suite) do
    ActiveModel::Validations.include(SEPA::TestValidationHelpers)
  end
  config.disable_monkey_patching!

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
